#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bash $HOME/.config/bspwm/starter.sh &
bash $HOME/.config/bspwm/lock.sh &
#picom -b &
#qv2ray &
#klipper &
#feh --bg-fill ~/Pictures/Mac/Daylight/macOS-Big-Sur-Daylight-Wallpaper-8.jpg &
#$HOME/.config/polybar/launch.sh --shades & 
#wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-A-0 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

# Border colors
bspc config normal_border_color  "#373C38"
bspc config focused_border_color "#51A8DD"
bspc config urgent_border_color  "#B58900"
bspc config presel_border_color  "#7DB9DE"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Google-chrome desktop='^2' follow=on
bspc rule -a jetbrains-idea desktop='^3' follow=on 
bspc rule -a obsidian desktop='^4' follow=on 
bspc rule -a code desktop='^5' follow=on 
